import quests from './quests.json';
import {weapons,weaponState,loadWeapons,toggleWeapon,restoreWeapons,questWeaponBadge,questWeaponDetails,renderWeapons,exportWeapons} from './weapons.js';
import {requestProgress} from './browser-progress.js';
import {encodeProgress} from './progress-text.js';
import {parseProgressImport} from './import-progress.js';
import {attachMapNavigation} from './map-navigation.js';
import {STORAGE_KEY,WEAPONS_STORAGE_KEY, filterQuests} from './progress.js';
const categories = {
 main:['Main missions','#f2f43d'],phantom:['Phantom Liberty','#f340ec'],side:['Side missions','#00bfff'],gig:['Gigs','#39ce35'],cyberpsycho:['Cyberpsycho sightings','#00d5d5'],ncpd:['NCPD scanner','#8e89ff'],tarot:['Tarot','#bd53ff'],criminal:['Criminal activity','#00e6b1'],interlude:['Main interludes','#f2f43d'],'side-interlude':['Side interludes','#00bfff'],ending:['Endings','#f2f43d'],'ending-phantom':['Phantom Liberty endings','#f340ec']
};
const state={category:'all',status:'all',search:'',view:'list',sort:'map',zoom:300,selected:null};
let completed=new Set(),storageOK=false,busy=true;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
function toast(message){$('#toast')?.remove();const el=document.createElement('div');el.id='toast';el.role='status';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),3500);}
function fileStatus(text){$('#save').textContent=text;$('.online').textContent=text;}
async function loadProgress(){
 if(!busy){busy=true;}
 try{
  let data=await requestProgress();
  if(!data.initialized){
   data=await requestProgress({type:'initialize',completed:[]});
  }
  completed=new Set(data.completed);storageOK=true;fileStatus('● Saved in this browser');renderStats();renderResults();
 }catch(e){storageOK=false;fileStatus('⚠ Browser save unavailable');toast(e.message);}
 finally{busy=false;}
}
async function saveAction(action){
 if(busy||(!storageOK&&action.type!=='replace')){toast(busy?'Please wait for saving to finish.':'Reload or import a backup to restore browser progress.');renderResults();return false;}
 busy=true;fileStatus('◌ Saving in this browser…');
 try{const data=await requestProgress(action);completed=new Set(data.completed);storageOK=true;fileStatus('● Saved in this browser');return true;}
 catch(e){fileStatus('⚠ Save failed — try again');toast(e.message);return false;}
 finally{busy=false;renderStats();renderNav();renderResults();}
}
async function toggle(id){await saveAction({type:'quest',id,done:!completed.has(id)});document.querySelector(`[data-quest="${id}"], [data-map-quest="${id}"]`)?.focus({preventScroll:true});}
function renderNav(){ $('#nav').innerHTML=`<button class="nav-button ${state.category==='all'&&!['legend','weapons'].includes(state.view)?'active':''}" data-category="all"><span>▦</span> All quests <span class="count">${quests.length}</span></button>`+Object.entries(categories).map(([id,[label,color]])=>`<button class="nav-button ${state.category===id&&!['legend','weapons'].includes(state.view)?'active':''}" data-category="${id}"><i class="dot" style="--c:${color}"></i>${label}<span class="count">${quests.filter(q=>q.category===id).length}</span></button>`).join('')+`<button class="nav-button ${state.view==='weapons'?'active':''}" data-view="weapons"><span>◇</span> Iconic weapons <span class="count">${weapons.length}</span></button>`; }
function renderStats(){const total=quests.length,done=completed.size,pct=Math.round(done/total*1000)/10;$('#stats').innerHTML=`<article class="stat"><div class="mono label">Your journey</div><div class="stat-value yellow">${pct}<small> % complete</small></div><div class="progress" role="progressbar" aria-label="Quest completion" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${total}"><i style="width:${done/total*100}%"></i></div></article><article class="stat"><div class="mono label">Quests completed</div><div class="stat-value">${String(done).padStart(2,'0')} <small>/ ${total}</small></div><div class="stat-foot">Every job leaves a mark.</div></article><article class="stat"><div class="mono label">Still out there</div><div class="stat-value">${total-done}<small> quests</small></div><div class="stat-foot">Night City isn't done with you.</div></article>`;}
function list(){let rows=filterQuests(quests,completed,state);if(state.sort==='az')rows.sort((a,b)=>a.name.localeCompare(b.name));return `<div class="list-head mono"><span>${rows.length} ${rows.length===1?'entry':'entries'} · ${state.category==='all'?'All categories':categories[state.category][0]}</span><span>Mark your milestones</span></div>`+(rows.length?rows.map(q=>`<article class="quest-row ${completed.has(q.id)?'done':''}" style="--c:${categories[q.category][1]}"><input class="check" type="checkbox" data-quest="${q.id}" aria-label="Complete ${escape(q.name)}" ${completed.has(q.id)?'checked':''}><div class="quest-copy"><div class="quest-name">${escape(q.name)}</div><div class="quest-meta">${escape(q.contact||'Night City')} ${q.category.includes('ending')?' / BRANCH OUTCOME':''}</div></div>${questWeaponBadge(q)}<span class="tag">${categories[q.category][0]}</span><button class="map-link" data-locate="${q.id}" title="Locate ${escape(q.name)} on map" aria-label="Locate ${escape(q.name)} on map">↗</button></article>`).join(''):`<div class="empty">${quests.length===completed.size?'All mapped quests complete. See you in the big leagues.':'No quests match these filters.'}<br><button class="btn" id="clear-filters" style="margin-top:18px">Clear filters</button></div>`);}
let mapNavigation;
function selectedQuest(){
 const q=quests.find(q=>q.id===state.selected);
 if(!q)return `<div class="map-detail empty-detail"><span class="eyebrow">QUEST INTEL</span><h3>Select a quest</h3><p>Click any box to see its name and mark it complete. Drag the canvas to explore the mission tree.</p></div>`;
 return `<div class="map-detail" style="--c:${categories[q.category][1]}"><span class="tag">${categories[q.category][0]}</span><h3>${escape(q.name)}</h3><p>${escape(q.contact||'Night City')}</p><div class="detail-status">${completed.has(q.id)?'✓ Completed':'○ Not completed'}</div><button class="btn primary" data-complete-selected="${q.id}">${completed.has(q.id)?'Mark incomplete':'Mark complete'}</button><button class="btn" data-journal-quest="${q.id}">Show in journal ↗</button>${questWeaponDetails(q)}<p class="detail-hint">Follow the original connections for quest order. Decisions and prerequisites are explained in the legend.</p></div>`;
}
function map(){
 const matches=filterQuests(quests,completed,state),ids=new Set(matches.map(q=>q.id));
 const filtering=state.search||state.category!=='all'||state.status!=='all';
 return `<div class="map-controls"><div class="zoom-buttons"><button class="btn" id="zoom-out" aria-label="Zoom out">−</button><span id="zoom-label">${Math.round(state.zoom)}%</span><button class="btn" id="zoom-in" aria-label="Zoom in">+</button><button class="btn" id="fit-map">Fit map</button></div><span class="map-help">Drag to pan · Ctrl/⌘ + scroll to zoom · + / − keys</span><button class="btn" id="expand-map">${$('#journal')?.classList.contains('expanded-map')?'Close expanded view':'Expand map ⛶'}</button></div>
 <div class="map-layout"><div class="map-scroll" tabindex="0" role="region" aria-label="Interactive quest flowchart"><div class="map-canvas" style="width:${state.zoom}%"><img draggable="false" src="./quest-map.png" alt="Original quest flowchart with sequence connections, branching choices, and legend">${quests.map(q=>`<button class="map-node ${completed.has(q.id)?'done':''} ${state.selected===q.id?'selected':''} ${filtering?(ids.has(q.id)?'matched':'dimmed'):''}" data-map-quest="${q.id}" title="${escape(q.name)} — ${completed.has(q.id)?'Completed':'Not completed'}" aria-label="Select ${escape(q.name)}" aria-pressed="${state.selected===q.id}" style="--c:${categories[q.category][1]};left:${q.x/9984*100}%;top:${q.y/7936*100}%;width:${q.w/9984*100}%;height:${q.h/7936*100}%"></button>`).join('')}</div></div><div class="map-panel">${selectedQuest()}<div class="map-matches"><div class="mono">${matches.length} matching entries</div>${filtering?matches.map(q=>`<button class="match-link" data-focus-quest="${q.id}"><i class="dot" style="--c:${categories[q.category][1]}"></i><span>${escape(q.name)}</span>${completed.has(q.id)?'✓':'↗'}</button>`).join('')||'<p>No matches. Try another search or category.</p>':'<p>Search or choose a category to highlight quests and jump to a result.</p>'}</div></div></div><div class="map-caption mono">Original connections preserved · Selected: outline · Completed: checkmark · <a href="./quest-map.png" target="_blank" rel="noopener">Open original ↗</a><br>Flowchart by u/rolux · <a href="https://www.reddit.com/r/cyberpunkgame/comments/177pi79/cyberpunk_20_phantom_liberty_mission_flowchart/" target="_blank" rel="noopener noreferrer">Source: r/cyberpunkgame ↗</a></div>`;
}
function focusQuest(id){
 state.selected=id;state.zoom=Math.max(state.zoom,450);renderResults();
 const q=quests.find(q=>q.id===id),sc=$('.map-scroll'),canvas=$('.map-canvas');
 sc.scrollLeft=(q.x+q.w/2)/9984*canvas.clientWidth-sc.clientWidth/2;
 sc.scrollTop=(q.y+q.h/2)/7936*canvas.clientHeight-sc.clientHeight/2;
 document.querySelector(`[data-map-quest="${id}"]`)?.focus({preventScroll:true});
}
function legend(){return `<div class="legend-grid">${Object.entries(categories).map(([key,[label,color]])=>`<div class="legend-item"><i class="dot" style="--c:${color};width:20px;height:20px;${key.includes('interlude')?'background:repeating-linear-gradient(135deg,var(--c),var(--c) 3px,#666 3px,#666 6px);':''}${key.includes('ending')?'background:#000;border:1px solid var(--c);':''}"></i>${label}</div>`).join('')}</div><div class="legend-note"><strong>Reading the mission tree</strong><br>Single connections show sequential missions. Parallel connections allow either order. A split can lead to both missions; a <strong>!</strong> marks a decision between branches. A <strong>+</strong> requires both preceding missions. Nested connections mark missions that take place during another mission.<br><br>Striped boxes are interludes. Black boxes are endings, with yellow or magenta borders for the base game or Phantom Liberty.<br><br><strong>Your completion goal</strong><br>This journal covers the entries in your supplied map, including separate tarot cards and repeated interludes. Alternative lifepaths and endings may require multiple playthroughs or reloading saves. Completion is manual; the journal does not infer unlocked quests or connect to game saves.</div>`;}
function renderResults(){const sc=$('.map-scroll');const pos=sc?{x:sc.scrollLeft,y:sc.scrollTop}:null;$('#results').innerHTML=state.view==='weapons'?renderWeapons(state,completed):state.view==='map'?map():state.view==='legend'?legend():list();if(state.view==='map'){mapNavigation=attachMapNavigation($('.map-scroll'),{zoom:state.zoom,onZoom:value=>{state.zoom=value;$('#zoom-label').textContent=`${Math.round(value)}%`;}});}if(pos&&state.view==='map'){ $('.map-scroll').scrollLeft=pos.x;$('.map-scroll').scrollTop=pos.y;}}
function renderSection(){ $('#section-title').textContent=state.view==='weapons'?'ICONIC WEAPONS':state.view==='legend'?'THE MAP LEGEND':state.view==='map'?'MISSION TREE':state.category==='all'?'QUEST JOURNAL':categories[state.category][0].toUpperCase();$('#search').setAttribute('aria-label',state.view==='weapons'?'Search weapons':'Search quests');$('#search').placeholder=state.view==='weapons'?'Search weapons, missions, acquisition notes…':'Search quests, characters, fixers...';$('#status').options[1].textContent=state.view==='weapons'?'Not collected':'Not completed';$('#status').options[2].textContent=state.view==='weapons'?'Collected':'Completed';$('#filters').hidden=state.view==='legend';$('#sort').hidden=state.view!=='list';if(state.view!=='map')$('#journal').classList.remove('expanded-map');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));renderResults();}
$('#app').innerHTML=`<aside><div class="brand">NIGHT CITY<em>_</em></div><div class="brand-sub mono">A COMPLETIONIST'S JOURNAL</div><div class="nav-label mono">The database</div><nav id="nav"></nav><div class="sidebar-bottom"><span class="online">◌ LOADING BROWSER PROGRESS</span><br>Your city. Your pace.<br>One quest at a time.</div></aside><main><header class="topbar"><div class="mono">CYBERPUNK 2077 <span style="margin:0 10px;color:#47554a">/</span> <strong>QUEST TRACKER</strong></div><div id="save" class="mono save-status">◌ Loading browser progress…</div></header><section class="hero"><div class="eyebrow">WELCOME BACK, MERC.</div><h1>UNFINISHED <span>BUSINESS.</span></h1><p>A whole city of stories. Keep track of every one.<br>Your path to completing Cyberpunk 2077 & Phantom Liberty.</p><div class="hero-actions"><button class="btn primary" id="continue">Explore the journal ↘</button><button class="btn" id="export">↓ Export quest progress</button><button class="btn" id="import">↑ Import quest backup</button><input type="file" id="import-file" accept="text/plain,.txt,application/json,.json" hidden></div></section><section class="stats" id="stats" aria-label="Completion overview"></section><section id="journal"><div class="section-title"><h2 id="section-title">QUEST JOURNAL</h2><div class="segmented"><button class="active" data-view="list">☷ List</button><button data-view="map">⌘ Mission tree</button><button data-view="legend">◇ Legend</button></div></div><div id="filters"><div class="toolbar"><label class="search"><span>⌕</span><input id="search" type="search" placeholder="Search quests, characters, fixers..." aria-label="Search quests"></label><select id="status" aria-label="Filter by completion"><option value="all">All statuses</option><option value="remaining">Not completed</option><option value="completed">Completed</option></select><select id="sort" aria-label="Sort quests"><option value="map">Map grouping</option><option value="az">Name: A–Z</option></select></div></div><div id="results"></div></section><footer><span>BASED ON YOUR MISSION TREE · INCLUDES PHANTOM LIBERTY<br>Saved in this browser · Export backups before clearing browser data.</span><span>MAKE YOUR MARK.<br>LEAVE NO STORY UNTOLD.</span></footer></main><dialog id="import-dialog"><h2>RESTORE PROGRESS?</h2><p id="import-summary"></p><div class="hero-actions"><button class="btn primary" id="confirm-import">Restore backup</button><button class="btn" id="cancel-import">Cancel</button></div></dialog>`;
renderNav();renderStats();renderResults();
loadProgress();
loadWeapons().then(()=>{if(['weapons','map'].includes(state.view))renderResults();});
let pendingImport=null,pendingImportKind='quests';
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.category){state.category=b.dataset.category;if(['legend','weapons'].includes(state.view))state.view='list';renderNav();renderSection();}if(b.dataset.view){state.view=b.dataset.view;if(state.view==='weapons'){state.search='';state.status='all';weaponState.questId=null;$('#search').value='';$('#status').value='all';}renderNav();renderSection();}if(b.dataset.mapQuest){state.selected=b.dataset.mapQuest;renderResults();}
if(b.dataset.weaponsFor){state.view='weapons';weaponState.questId=b.dataset.weaponsFor;weaponState.group='all';state.search='';state.status='all';$('#search').value='';$('#status').value='all';renderNav();renderSection();}
if(b.id==='clear-weapon-quest'){weaponState.questId=null;renderResults();}
if(b.id==='export-weapons')exportWeapons();
if(b.id==='import-weapons'){pendingImportKind='weapons';$('#import-file').click();}
if(b.id==='retry-weapons'){await loadWeapons();renderResults();}
if(b.dataset.completeSelected)toggle(b.dataset.completeSelected);
if(b.dataset.focusQuest)focusQuest(b.dataset.focusQuest);
if(b.dataset.journalQuest){const q=quests.find(q=>q.id===b.dataset.journalQuest);state.view='list';state.category='all';state.status='all';state.search=q.name;$('#search').value=q.name;$('#status').value='all';renderNav();renderSection();}
if(b.dataset.locate){state.search='';state.status='all';state.category='all';$('#search').value='';$('#status').value='all';state.view='map';renderNav();state.selected=b.dataset.locate;renderSection();focusQuest(b.dataset.locate);$('#journal').scrollIntoView({behavior:'smooth'});}
if(b.id==='zoom-in'||b.id==='zoom-out')mapNavigation.setZoom(state.zoom*(b.id==='zoom-in'?1.25:.8));
if(b.id==='fit-map'){mapNavigation.setZoom(100);$('.map-scroll').scrollTo(0,0);}
if(b.id==='expand-map'){$('#journal').classList.toggle('expanded-map');b.textContent=$('#journal').classList.contains('expanded-map')?'Close expanded view':'Expand map ⛶';if(state.selected)focusQuest(state.selected);}
if(b.id==='clear-filters'){state.category='all';state.status='all';state.search='';$('#search').value='';$('#status').value='all';renderNav();renderSection();}if(b.id==='continue'){$('#journal').scrollIntoView({behavior:'smooth'});$('#search').focus({preventScroll:true});}if(b.id==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([encodeProgress(completed,quests)],{type:'text/plain'}));a.download=`night-city-progress-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Progress backup downloaded.');}if(b.id==='import'){pendingImportKind='quests';$('#import-file').click();}if(b.id==='cancel-import'){$('#import-dialog').close();pendingImport=null;}if(b.id==='confirm-import'&&pendingImport){const success=pendingImportKind==='weapons'?await restoreWeapons(pendingImport):await saveAction({type:'replace',completed:[...pendingImport]});if(success){pendingImport=null;$('#import-dialog').close();renderResults();toast('Backup imported. Saved in this browser.');}else if(pendingImportKind==='weapons'){toast(weaponState.error||'Please wait for the current save.');}}});
document.addEventListener('change',async e=>{if(e.target.dataset.weapon){const id=e.target.dataset.weapon;const pending=toggleWeapon(id);renderResults();if(!await pending)toast(weaponState.error||'Wait for weapon progress to finish loading.');renderResults();document.querySelector(`[data-weapon="${id}"]`)?.focus({preventScroll:true});}if(e.target.id==='weapon-group'){weaponState.group=e.target.value;renderResults();}if(e.target.dataset.quest)toggle(e.target.dataset.quest);if(e.target.id==='status'){state.status=e.target.value;renderResults();}if(e.target.id==='sort'){state.sort=e.target.value;renderResults();}if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;try{const text=await file.text();pendingImport=parseProgressImport(text,pendingImportKind==='weapons'?weapons:quests);const current=pendingImportKind==='weapons'?weaponState.collected.size:completed.size;$('#import-summary').textContent=`This ${pendingImportKind} backup contains ${pendingImport.size} checked entries. Importing it will replace the ${current} checked ${pendingImportKind} in this browser. Your other checklist stays as it is.`;$('#import-dialog').showModal();}catch(err){toast(err.message||'Unable to read backup.');}e.target.value='';}});
$('#search').addEventListener('input',e=>{state.search=e.target.value;renderResults();});
window.addEventListener('focus',()=>{if(!busy)loadProgress();loadWeapons().then(()=>{if(['weapons','map'].includes(state.view))renderResults();});});

document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#journal').classList.contains('expanded-map')){$('#journal').classList.remove('expanded-map');$('#expand-map').textContent='Expand map ⛶';if(state.selected)focusQuest(state.selected);$('#expand-map').focus();}});

window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY||e.key===null){if(!busy)loadProgress();}if(e.key===WEAPONS_STORAGE_KEY||e.key===null){loadWeapons().then(()=>renderResults());}});
